/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IsArmstrongNumber;
import java.util.Scanner;
import java.util.Stack;
;
public class App {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Integer number;
        System.out.println("Introduce un número: ");
        number = in.nextInt();
        in.close();

        if (Utils.IsArmstrongNumber(number)) {
            System.out.println(number.toString() + " es un número de armstrong");
        } else {
            System.out.println(number.toString() + " no es un número de armstrong");
        }
    }
}
